language: node_js

node_js:
- '0.10'

branches:
  only:
  - master
  - sce

before_script:
- git submodule update --init --recursive
- npm install -g grunt-cli
- grunt --version

after_success:
- grunt build

notifications:
  hipchat: 1fbdbbbaa517c485f935a6d72f1110@239240
  on_success: never