language: node_js

node_js:
- '0.10'

branches:
  only:
  - master

before_script:
- git submodule update --init --recursive
- npm install -g grunt-cli
- grunt --version

notifications:
  hipchat: 1fbdbbbaa517c485f935a6d72f1110@239240

env:
  global:
    secure: ReB6az6ZTViFDI//sFRcjsS+yA0MXFOnMGicBlSAc3Px/9ggzs8Zbzt7FMnO7AHHUV/BGs8IsITWYaAM8rs2+8I27TaBcKZAkMT7+6m7lljnnEkXAgH9F46BROf6ABBA66oFpg/XAR+k0QJhRFnqi5bD7+7KbLtyLtJHw54QrSw=
